import React from "react";
import { Link, Route, Switch, useRouteMatch } from "react-router-dom";
import Navbar from "../Navbar";
import MathCategory from "./MathCategory"; // Unified component for Math categories

const MathIndex = () => {
  let { path, url } = useRouteMatch();

  return (
    <div className="learning-process">
      <Navbar />
      <div className="content-container">
        <div className="learning-content">
          <h1>Math Learning Process</h1>
          <p>
            Welcome to the Math Learning Process! Here, you can practice various
            math topics to improve your skills.
          </p>
          <p>
            Select a category from the list below to get started. Each category
            will present you with math problems generated by an AI to solve.
          </p>
        </div>
        <div className="math-categories">
          <h2>Math Categories</h2>
          <ol className="category-list">
            {["addition", "subtraction", "multiplication", "division"].map(
              (category) => (
                <li key={category}>
                  <Link to={`${url}/${category}`}>
                    {category.charAt(0).toUpperCase() + category.slice(1)}
                  </Link>
                </li>
              )
            )}
          </ol>
        </div>
        <Switch>
          <Route exact path={path}>
            <div className="selected-category">
              <h3>Please select a math category to start learning.</h3>
            </div>
          </Route>
          <Route path={`${path}/:category`} component={MathCategory} />
        </Switch>
      </div>
    </div>
  );
};

export default MathIndex;
